version: "3.7"

services:
  web:
    container_name: "application"

    build: .

    command: bash -c "uvicorn ma1n:app --reload --host 0.0.0.0 --port 8000"

    env_file:
      - .env

    depends_on:
      - db

    ports:
      - "8000:8000"
  db:
    container_name: "postgres_db"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_DB=finance_management_db


    image: postgres:15

    env_file:
      - .env

    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4

    ports:
      - "5555:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin

    depends_on:
      - db

    restart: unless-stopped

