version: "3.7"

services:
  web:
    container_name: "application"

    build: .

    command: bash -c "uvicorn ma1n:app --reload --host 0.0.0.0 --port 8000"

    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SERVER=db
      - DB_PORT=5432
      - DB_NAME=finance_management_db
      - SECRET_KEY=f019b97acc525baa8291a467a1a40483cf1f9dc343a0b41584e1277f9a65ab47d07feaaae19f0ceadf31b6ccd6a5b39c5cd4f7edfe186a6dc
      - SALT=$2b$12$5kw1seI/xsJXiGCK6f..T.
      - ACCESS_TOKEN_EXPIRATION_TIME=10
      - REFRESH_TOKEN_EXPIRATION_TIME=30

    depends_on:
      - db

    ports:
      - "8000:8000"

  db:
    container_name: "postgres_db"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_DB=finance_management_db

    image: postgres:15

    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"

  frontend:
    container_name: "frontend-app"
    build: "../frontend"
    ports:
      - "5173:5173"

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin

    depends_on:
      - db

    restart: unless-stopped

